#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TriangleLabelView.Resource", IsApplication=false)]

namespace TriangleLabelView
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public static int backgroundColor = 2130771968;
			
			// aapt resource value: 0x7f01000c
			public static int corner = 2130771980;
			
			// aapt resource value: 0x7f010009
			public static int labelBottomPadding = 2130771977;
			
			// aapt resource value: 0x7f010008
			public static int labelCenterPadding = 2130771976;
			
			// aapt resource value: 0x7f010007
			public static int labelTopPadding = 2130771975;
			
			// aapt resource value: 0x7f010003
			public static int primaryText = 2130771971;
			
			// aapt resource value: 0x7f010001
			public static int primaryTextColor = 2130771969;
			
			// aapt resource value: 0x7f010005
			public static int primaryTextSize = 2130771973;
			
			// aapt resource value: 0x7f01000a
			public static int primaryTextStyle = 2130771978;
			
			// aapt resource value: 0x7f010004
			public static int secondaryText = 2130771972;
			
			// aapt resource value: 0x7f010002
			public static int secondaryTextColor = 2130771970;
			
			// aapt resource value: 0x7f010006
			public static int secondaryTextSize = 2130771974;
			
			// aapt resource value: 0x7f01000b
			public static int secondaryTextStyle = 2130771979;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f030000
			public static int bold = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int italic = 2130903041;
			
			// aapt resource value: 0x7f030003
			public static int leftBottom = 2130903043;
			
			// aapt resource value: 0x7f030004
			public static int leftTop = 2130903044;
			
			// aapt resource value: 0x7f030002
			public static int normal = 2130903042;
			
			// aapt resource value: 0x7f030005
			public static int rightBottom = 2130903045;
			
			// aapt resource value: 0x7f030006
			public static int rightTop = 2130903046;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f020000
			public static int library_name = 2130837504;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] TriangleLabelView = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980};
			
			// aapt resource value: 0
			public static int TriangleLabelView_backgroundColor = 0;
			
			// aapt resource value: 12
			public static int TriangleLabelView_corner = 12;
			
			// aapt resource value: 9
			public static int TriangleLabelView_labelBottomPadding = 9;
			
			// aapt resource value: 8
			public static int TriangleLabelView_labelCenterPadding = 8;
			
			// aapt resource value: 7
			public static int TriangleLabelView_labelTopPadding = 7;
			
			// aapt resource value: 3
			public static int TriangleLabelView_primaryText = 3;
			
			// aapt resource value: 1
			public static int TriangleLabelView_primaryTextColor = 1;
			
			// aapt resource value: 5
			public static int TriangleLabelView_primaryTextSize = 5;
			
			// aapt resource value: 10
			public static int TriangleLabelView_primaryTextStyle = 10;
			
			// aapt resource value: 4
			public static int TriangleLabelView_secondaryText = 4;
			
			// aapt resource value: 2
			public static int TriangleLabelView_secondaryTextColor = 2;
			
			// aapt resource value: 6
			public static int TriangleLabelView_secondaryTextSize = 6;
			
			// aapt resource value: 11
			public static int TriangleLabelView_secondaryTextStyle = 11;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
